spring:
 main:
  sources: biz.letsweb.camel.integration.IntegratorApp
  web_environment: true
 datasource:
  name: testds
  url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  username: toks
  password: pass
  driver-class-name: org.h2.Driver
  initialize: true
 h2:
  console:
   enabled: true
   path: /h2-console
shell.auth.simple.user.password: password
testEndpoint: mock:result
jettyProxyEndpoint1: jetty:http://localhost:8083?matchOnUriPrefix=true&throwExceptionOnFailure=false
jettyProxyEndpoint2: jetty:http://localhost:8081?matchOnUriPrefix=true&throwExceptionOnFailure=false
app1: http://localhost:8070/rest-one?throwExceptionOnFailure=true&bridgeEndpoint=true&urlRewrite=#urlRewriteFilter
sqltest: sql:SELECT * FROM property?dataSource=#dataSource
camel:
    prod:
     loadbalancer:
      component: jetty
      host: http://localhost:8083
      matchOnUriPrefix: true
      throwExceptionOnFailure: false
