spring.main.sources: biz.letsweb.camel.integration.IntegratorApp
shell.auth.simple.user.password: password
testEndpoint: mock:result
jettyProxyEndpoint1: jetty:http://localhost:8083?matchOnUriPrefix=true&throwExceptionOnFailure=false
jettyProxyEndpoint2: jetty:http://localhost:8081?matchOnUriPrefix=true&throwExceptionOnFailure=false
app1: http://localhost:8070/rest-one?throwExceptionOnFailure=true&bridgeEndpoint=true&urlRewrite=#urlRewriteFilter
spring.main.web_environment: false
camel:
    prod:
     loadbalancer:
      component: jetty
      host: http://localhost:8083
      matchOnUriPrefix: true
      throwExceptionOnFailure: false